# -*- coding: utf-8 -*-
"""day1 python basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLdu6tel_p9Zdt6zaqh8-znE3A8QzStp
"""

age=input("enter your age")
if age>=18:
  print("you are an adult now")
else:
  print("you can go watch cartoons")

#asking for a number and creating a variable.
var=1
num=int(input("enter a number"))
#Checking for odd or even
if num%2==0:
  print("Even")
else:
  print("Odd")
#while loop to print till number
while var<=num:
  print(var)
  var=var+1

#asking for a number
num=int(input("enter a number"))
div_num=0
#checking for divisiblity by 3.
for i in range(1,num+1):
  if i%3==0:
    print(i)
    div_num+=1
print("it was divisible", div_num, "number of time.")

#asking for a number
num=int(input("enter a number"))

#Checking for odd or even
if num%2==0:
  print("Even")
else:
  print("Odd")
#checking for +ve or -ve
if num>=1:
  print("Number is positive")
elif num<0:
  print("Number is negative")
else:
  print("Number is zero")
#printing the table
for i in range(1,11):
  print(num," * ",i," = ",num*i)