# -*- coding: utf-8 -*-
"""Day 2 - Lists Practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLvWLKWttJA7i3bAUf_Bt1Xz0IGyV0zJ
"""

"""
Day 2 - Lists Practice

This program:
1. Takes 5 numbers from the user
2. Stores them in a list
3. Finds the largest and smallest number manually and print the diffrence between largest and smallest number
4. Prints the results

Goal: Practice list logic and comparison.
"""
new_list=[]
for i in range(5):
    new_list.append(int(input("Enter a number: ")))
#initializing min and max variables
largest=new_list[0]
smallest=new_list[0]
for i in new_list:
  if i>largest:
    largest=i
  if i<smallest:
    smallest=i
print("largest number is", largest)
print("smallest number is", smallest)
print(f"the difference bettween {largest} and {smallest} is {largest-smallest}")

#Write a program that:
#Creates an empty list
#Takes 3 numbers from user
#Stores them
#Prints the list
#Prints the first and last element
new_list=[]
for i in range(3):
    new_list.append(int(input("Enter a number: ")))
print(new_list)
print("first element is", new_list[0])
print("last element is", new_list[-1])