# -*- coding: utf-8 -*-
"""list practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V3EUUbs_-r0yQbkCSLf5k3hwRBKGQc8e
"""

"""
Takes 10 numbers from the user.

Stores them in a list.

Prints:

The list

The largest number

The smallest number

The average

How many numbers are even

How many numbers are odd

Bonus:

Print the second largest number
"""

new_list = []
for i in range(10): # Changed to 10 numbers
  new_list.append(int(input(f"Enter number {i+1}: ")))

print("The list:", new_list)

# Calculate largest, smallest, average, even, and odd numbers
highest = new_list[0] # Initialize with the first element
lowest = new_list[0]  # Initialize with the first element

for num in new_list:
  if num > highest:
    highest = num
  if num < lowest:
    lowest = num

print("The largest number:", highest)
print("The smallest number:", lowest)

# Calculate average
average = sum(new_list) / len(new_list)
print("The average:", average)

# Count even and odd numbers
even_count = 0
odd_count = 0
for num in new_list:
  if num % 2 == 0:
    even_count += 1
  else:
    odd_count += 1

print("How many numbers are even:", even_count)
print("How many numbers are odd:", odd_count)